// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	Slug          string             `json:"slug"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	IsPublic      bool               `json:"is_public"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Visibility    string             `json:"visibility"`
}

type CartItem struct {
	ID          int64              `json:"id"`
	CartID      int64              `json:"cart_id"`
	Position    int32              `json:"position"`
	LinkID      int64              `json:"link_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	PriceText   pgtype.Text        `json:"price_text"`
	Retailer    pgtype.Text        `json:"retailer"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CartViewsDaily struct {
	CartID int64       `json:"cart_id"`
	Day    pgtype.Date `json:"day"`
	Views  int32       `json:"views"`
}

type ClickDaily struct {
	LinkID int64       `json:"link_id"`
	Day    pgtype.Date `json:"day"`
	Clicks int32       `json:"clicks"`
}

type ClickEvent struct {
	ID            int64              `json:"id"`
	LinkID        int64              `json:"link_id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	CountryCode   pgtype.Text        `json:"country_code"`
	UserAgentKind pgtype.Text        `json:"user_agent_kind"`
	RefererHost   pgtype.Text        `json:"referer_host"`
	VisitorHash   pgtype.Text        `json:"visitor_hash"`
}

type ExtensionToken struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Feedback struct {
	ID        int64              `json:"id"`
	Message   string             `json:"message"`
	Email     pgtype.Text        `json:"email"`
	Name      pgtype.Text        `json:"name"`
	Page      pgtype.Text        `json:"page"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Link struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	UserID      int64              `json:"user_id"`
	OriginalUrl string             `json:"original_url"`
	Retailer    string             `json:"retailer"`
	LinkType    string             `json:"link_type"`
	CartID      pgtype.Int8        `json:"cart_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
}

type OtpAttempt struct {
	ID         int64              `json:"id"`
	Phone      string             `json:"phone"`
	Ip         netip.Addr         `json:"ip"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

type User struct {
	ID          int64              `json:"id"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	GoogleSub   pgtype.Text        `json:"google_sub"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Handle      pgtype.Text        `json:"handle"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	BannedAt    pgtype.Timestamptz `json:"banned_at"`
}
