// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Per-day click totals across all of a user's cart links over the last 14 days.
	// links.cart_id is nullable; the JOIN naturally drops non-cart (single) links.
	AccountDailyClicks(ctx context.Context, userID int64) ([]AccountDailyClicksRow, error)
	// Per-day view totals across all of a user's carts over the last 14 days.
	// Only days with rows are returned; the service zero-fills the gaps.
	AccountDailyViews(ctx context.Context, userID int64) ([]AccountDailyViewsRow, error)
	// ─── CART ITEMS ────────────────────────────────────────────────────────────
	AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error)
	// All users (newest first, capped) with per-user cart/follower/following counts
	// for the admin user table.
	AdminListUsers(ctx context.Context) ([]AdminListUsersRow, error)
	// Platform-wide totals for the read-only admin overview. privateCarts is
	// derived in Go (carts - publicCarts) so this stays a single round-trip.
	AdminOverview(ctx context.Context) (AdminOverviewRow, error)
	// One user's non-archived carts (newest first) with product count and 7-day
	// views/clicks, for the admin per-user drill-down.
	AdminUserCarts(ctx context.Context, userID int64) ([]AdminUserCartsRow, error)
	ArchiveCart(ctx context.Context, id int64) error
	BumpCartViewsDaily(ctx context.Context, cartID int64) error
	BumpClickDaily(ctx context.Context, linkID int64) error
	CartClicks7d(ctx context.Context, cartID pgtype.Int8) (int64, error)
	CartReach7d(ctx context.Context, cartID pgtype.Int8) (int64, error)
	// ─── ANALYTICS (reads) ──────────────────────────────────────────────────────
	CartViews7d(ctx context.Context, cartID int64) (int64, error)
	CountFollowers(ctx context.Context, creatorID int64) (int64, error)
	// ─── CARTS ──────────────────────────────────────────────────────────────────
	CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error)
	// ─── EXTENSION TOKENS ────────────────────────────────────────────────────────
	CreateExtensionToken(ctx context.Context, arg CreateExtensionTokenParams) error
	// ─── LINKS ──────────────────────────────────────────────────────────────────
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	// Creators (users with >=1 public, non-archived cart) ranked by 7-day cart
	// views. cart_count counts public carts; follower_count via correlated
	// subquery to avoid join fan-out. viewer_id excludes the logged-in viewer from
	// their own results (a logged-out viewer passes 0, which matches no real user).
	DiscoverCreators(ctx context.Context, arg DiscoverCreatorsParams) ([]DiscoverCreatorsRow, error)
	// ─── FOLLOWS / CREATORS ──────────────────────────────────────────────────────
	FollowCreator(ctx context.Context, arg FollowCreatorParams) error
	GetCartByID(ctx context.Context, id int64) (Cart, error)
	// No is_public/visibility filter here: the service gates private carts so the
	// OWNER can still fetch their own. archived carts remain excluded.
	GetCartBySlug(ctx context.Context, slug string) (Cart, error)
	GetExtensionTokenByHash(ctx context.Context, tokenHash string) (GetExtensionTokenByHashRow, error)
	GetLinkBySlug(ctx context.Context, slug string) (Link, error)
	GetUserByGoogleSub(ctx context.Context, googleSub pgtype.Text) (User, error)
	GetUserByHandle(ctx context.Context, handle pgtype.Text) (User, error)
	// internal/db/queries.sql
	// ─── USERS ──────────────────────────────────────────────────────────────────
	GetUserByID(ctx context.Context, id int64) (User, error)
	// ─── ANALYTICS (writes) ────────────────────────────────────────────────────
	InsertClickEvent(ctx context.Context, arg InsertClickEventParams) error
	// ─── FEEDBACK ────────────────────────────────────────────────────────────────
	InsertFeedback(ctx context.Context, arg InsertFeedbackParams) error
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	ListCartItems(ctx context.Context, cartID int64) ([]ListCartItemsRow, error)
	ListCartsByUser(ctx context.Context, userID int64) ([]Cart, error)
	ListFeedback(ctx context.Context) ([]Feedback, error)
	// Public, non-archived carts owned by creators that $1 follows, newest first.
	ListFollowingCartIDs(ctx context.Context, arg ListFollowingCartIDsParams) ([]Cart, error)
	ListPublicCartsByUser(ctx context.Context, userID int64) ([]Cart, error)
	// Distinct cover images the user has used across their carts, most-recent
	// first — powers the "your covers" section of the cover picker.
	ListUserCoverImages(ctx context.Context, userID int64) ([]ListUserCoverImagesRow, error)
	NextCartItemPosition(ctx context.Context, cartID int64) (int32, error)
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	ReorderCartItem(ctx context.Context, arg ReorderCartItemParams) error
	// Creators (>=1 public, non-archived cart) whose handle or display name matches
	// the search term. pattern = '%term%' (substring filter); prefix = 'term%'
	// (prefix matches rank first). Mirrors DiscoverCreators' columns so the handler
	// can reuse the same row mapping.
	SearchCreators(ctx context.Context, arg SearchCreatorsParams) ([]SearchCreatorsRow, error)
	TouchExtensionToken(ctx context.Context, id int64) error
	UnfollowCreator(ctx context.Context, arg UnfollowCreatorParams) error
	UpdateCart(ctx context.Context, arg UpdateCartParams) (Cart, error)
	// Edit a product's display fields (the URL/retailer live on the link and stay
	// immutable — changing those is effectively a different product).
	UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (CartItem, error)
	UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
