// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	// internal/db/queries.sql
	// Real queries will be added in later plans. sqlc needs at least one entry
	// to generate, so we register a trivial one.
	PingNow(ctx context.Context) (interface{}, error)
}

var _ Querier = (*Queries)(nil)
