// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const pingNow = `-- name: PingNow :one

SELECT now() AS now
`

// internal/db/queries.sql
// Real queries will be added in later plans. sqlc needs at least one entry
// to generate, so we register a trivial one.
func (q *Queries) PingNow(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, pingNow)
	var now interface{}
	err := row.Scan(&now)
	return now, err
}
