// Font loader for `next/og` ImageResponse (satori).
//
// satori only accepts static TTF/OTF buffers — NOT woff2 or variable woff — so
// we ship static instances of the brand serif (Fraunces) and sans (Inter).
//
// RELIABILITY (standalone build): the TTF bytes are embedded as base64 in the
// adjacent `data.ts` module (generated by scripts/gen-share-fonts.mjs) rather
// than read from disk. A relative `fs.readFile` of a sibling .ttf is NOT traced
// into `.next/standalone`, so the file wouldn't exist at runtime; embedding the
// bytes makes them part of the JS bundle that always ships. Buffers are decoded
// once and memoized.

import { interRegular, interSemiBold, frauncesRegular, frauncesSemiBold } from "./data";

export type SatoriFont = {
  name: string;
  data: ArrayBuffer;
  weight: 400 | 600;
  style: "normal";
};

// Decode a base64 string to a tight ArrayBuffer (satori wants an ArrayBuffer).
function decode(b64: string): ArrayBuffer {
  const buf = Buffer.from(b64, "base64");
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
}

let cache: SatoriFont[] | null = null;

// Load the four static faces used across all share cards. Memoized.
export function loadShareFonts(): SatoriFont[] {
  if (cache) return cache;
  cache = [
    { name: "Inter", data: decode(interRegular), weight: 400, style: "normal" },
    { name: "Inter", data: decode(interSemiBold), weight: 600, style: "normal" },
    { name: "Fraunces", data: decode(frauncesRegular), weight: 400, style: "normal" },
    { name: "Fraunces", data: decode(frauncesSemiBold), weight: 600, style: "normal" },
  ];
  return cache;
}
